name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Using graph charts (plugin_stargazers)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stargazers.graph.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph
          plugin_traffic: yes
      - name: GitHub City
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.skyline.city.svg
          token: NOT_NEEDED
          base: ''
          plugin_skyline: yes
          plugin_skyline_year: 2026
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          plugin_skyline_settings: |
            {
              "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
              "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
              "wait": 4,
              "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
            }
